[package]
name = "rust-sql-gui"
version = "1.0.0-alpha.3"
description = "PostgreSQL GUI written in Rust"
authors = ["Daniel Boros"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
common = { path = "../common" }
tauri = { version = "1.5.2", features = [ "shell-open", "fs-all"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
tokio = "1.34.0"
tokio-postgres = "0.7.10"
chrono = "0.4.31"
sled = "0.34.7"
strum = "0.25.0"
strum_macros = "0.25.3"



[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
