[package]
name = "rust-sql-gui-ui"
version = "1.0.0-alpha.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
leptos = { version = "0.5.4", features = ["csr", "nightly"] }
leptos_devtools = { git = "https://github.com/luoxiaozero/leptos-devtools" }
serde = { version = "1.0.192", features = ["derive"] }
serde-wasm-bindgen = "0.6.1"
wasm-bindgen = { version ="0.2.88", features = ["serde-serialize"] }
js-sys = "0.3.65"
leptos-use = { version = "0.8.2", features = ["serde", "serde_json", "storage"]}
leptos_icons = { version = "0.1.0", features = ["HiBars4OutlineLg", "HiCircleStackOutlineLg", "HiTableCellsOutlineLg"] } # https://carlosted.github.io/icondata/
serde_json = "1.0.108"
wasm-bindgen-futures = "0.4.39"
monaco = "0.4.0"
# tauri = { version = "1.5.3", features = ["dialog"] }
thaw = "0.1.3"

[workspace]
members = ["src-tauri"]
