[target.x86_64-pc-windows-msvc]
linker = "lld"
rustflags = [
  "-Lnative=Users/danixx/.xwin/crt/lib/x86_64",
  "-Lnative=Users/danixx/.xwin/sdk/lib/um/x86_64",
  "-Lnative=Users/danixx/.xwin/sdk/lib/ucrt/x86_64"
]

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"